baseurl: 'https://arnobsanzam.github.io/odyssey'
languageCode: en-us
theme: terminal
paginate: 5
params:
  contentTypeName: posts
  themeColor: orange
  showMenuItems: 2
  fullWidthTheme: false
  centerTheme: true
  readingTime: true

languages:
  en:
    title: Arnob's Odyssey
    subtitle: 'A simple, retro theme for Hugo'
    keywords: ''
    copyright: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts
    params:
      Toc: true
      TocTitle: Contents
      logo:
        logoText: Arnob's Odyssey
        logoHomeLink: 'https://arnobsanzam.github.io/odyssey'
    menu:
      main:
        - identifier: blogs
          name: Blogs
          url: /blogs
          weight: 1
        - identifier: about
          name: Contact
          url: /contact
          weight: 2
        - identifier: showcase
          name: Showcase
          url: /showcase
        - identifier: solutions
          name: Problem Solving
          url: /problem-solving/problemsolving
          weight: 3
