baseurl = "https://arnobsanzam.github.io/odyssey"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Arnob's Odyssey"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Arnob's Odyssey"
      logoHomeLink = "https://arnobsanzam.github.io/odyssey"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blogs"
        name = "Blogs"
        url = "/blogs"
        [[languages.en.menu.main]]
        identifier = "about"
        name = "Contact"
        url = "/contact"
        [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
